# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/dlpack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fv1/dlpack.proto\x12\tdlpack.v1\";\n\rDLPackVersion\x12\x14\n\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n\x05minor\x18\x02 \x01(\rR\x05minor\"H\n\x08\x44LDevice\x12\x1f\n\x0b\x64\x65vice_type\x18\x01 \x01(\x05R\ndeviceType\x12\x1b\n\tdevice_id\x18\x02 \x01(\x05R\x08\x64\x65viceId\"J\n\nDLDataType\x12\x12\n\x04\x63ode\x18\x01 \x01(\rR\x04\x63ode\x12\x12\n\x04\x62its\x18\x02 \x01(\rR\x04\x62its\x12\x14\n\x05lanes\x18\x03 \x01(\rR\x05lanes\"\xdd\x01\n\x08\x44LTensor\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta\x12+\n\x06\x64\x65vice\x18\x02 \x01(\x0b\x32\x13.dlpack.v1.DLDeviceR\x06\x64\x65vice\x12\x12\n\x04ndim\x18\x03 \x01(\x05R\x04ndim\x12+\n\x05\x64type\x18\x04 \x01(\x0b\x32\x15.dlpack.v1.DLDataTypeR\x05\x64type\x12\x14\n\x05shape\x18\x05 \x03(\x03R\x05shape\x12\x18\n\x07strides\x18\x06 \x03(\x03R\x07strides\x12\x1f\n\x0b\x62yte_offset\x18\x07 \x01(\x04R\nbyteOffset\"\x8f\x01\n\x11\x44LTensorVersioned\x12\x32\n\x07version\x18\x01 \x01(\x0b\x32\x18.dlpack.v1.DLPackVersionR\x07version\x12\x14\n\x05\x66lags\x18\x02 \x01(\x03R\x05\x66lags\x12\x30\n\tdl_tensor\x18\x03 \x01(\x0b\x32\x13.dlpack.v1.DLTensorR\x08\x64lTensorBa\n\rcom.dlpack.v1B\x0b\x44lpackProtoP\x01\xa2\x02\x03\x44XX\xaa\x02\tDlpack.V1\xca\x02\tDlpack\\V1\xe2\x02\x15\x44lpack\\V1\\GPBMetadata\xea\x02\nDlpack::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.dlpack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\rcom.dlpack.v1B\013DlpackProtoP\001\242\002\003DXX\252\002\tDlpack.V1\312\002\tDlpack\\V1\342\002\025Dlpack\\V1\\GPBMetadata\352\002\nDlpack::V1'
  _globals['_DLPACKVERSION']._serialized_start=30
  _globals['_DLPACKVERSION']._serialized_end=89
  _globals['_DLDEVICE']._serialized_start=91
  _globals['_DLDEVICE']._serialized_end=163
  _globals['_DLDATATYPE']._serialized_start=165
  _globals['_DLDATATYPE']._serialized_end=239
  _globals['_DLTENSOR']._serialized_start=242
  _globals['_DLTENSOR']._serialized_end=463
  _globals['_DLTENSORVERSIONED']._serialized_start=466
  _globals['_DLTENSORVERSIONED']._serialized_end=609
# @@protoc_insertion_point(module_scope)
